# Generated by Django 2.2 on 2021-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ingestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='norm',
            field=models.IntegerField(default=1, verbose_name='Норма калорий'),
            preserve_default=False,
        ),
    ]
